# Generated by Django 4.1.4 on 2022-12-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_medical_information_last_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_information',
            name='last_donation',
            field=models.DateField(null=True),
        ),
    ]
